serve:
  listen: ":1080"
  admin_listen: "127.0.0.1:19090"
  ca_dir: "~/.gomitm/ca"
  dial_timeout: "10s"

mitm:
  all: false
  hosts:
    - "*.googlevideo.com"
    - "youtubei.googleapis.com"

modules:
  - name: GoogleHomeFunDemo
    enable: true
    path: "./modules/google-home-fun.sgmodule"
    arguments:
      文案: "今天也要快乐摸鱼"
  - name: YouTubeNoAds
    enable: false
    path: "https://raw.githubusercontent.com/iab0x00/ProxyRules/refs/heads/main/Rewrite/YouTubeNoAd.sgmodule"
    arguments:
      字幕翻译语言: "off"
      歌词翻译语言: "off"
      启用调试模式: false

capture:
  enabled: true
  max_entries: 1000
  max_body_bytes: 2097152
  content_types:
    - "application/json"
    - "text/*"
  har_out: "./tmp/session.har"
